releasing the FB pod pin
Innim/flutter_login_facebook pull request #102
Opened 2023-10-10 16:04 UTC by bsz0206

2024-03-30 13:14 UTC, Saifallak requested changes

2024-03-30 13:14 UTC, Saifallak commented on ios/flutter_login_facebook.podspec
> +  s.dependency 'FBSDKLoginKit', '~> 16.0.1'
```suggestion
  s.dependency 'FBSDKLoginKit', '~> 16.1'  
```

2024-03-30 13:14 UTC, Saifallak commented
can we merge it to support with facebook app events ? https://github.com/oddbit/flutter_facebook_app_events/pull/309

2024-04-16 11:58 UTC, lcsvcn commented
+1

2024-04-16 12:10 UTC, lcsvcn commented
@Saifallak I tested out your implementation is still telling:

```
 FBSDKLoginKit (~> 16.0.1) was resolved to 16.0.1, which depends on
        FBSDKCoreKit (= 16.0.1)
```
<img width="888" alt="Screenshot 2024-04-16 at 09 09 51" src="https://github.com/Innim/flutter_login_facebook/assets/6011385/4e6bd7d4-e9e3-4b68-b2ef-03993e7873f2">

2024-04-16 12:18 UTC, greymag commented
Version 17.0 requires support of the Limited login feature. See #108 for details. I'm closing this PR for now.

2024-04-16 12:18 UTC, closed without merging