Prevent millisecondsSinceEpoch Invalid value: Not in inclusive range - error on high Facebook API expiry responses
Innim/flutter_login_facebook pull request #66
Opened 2021-12-22 12:50 UTC by rogiervandenberg

In some situations on Android (e.g. Pixel 3 with Android 12 and the latest Update to Facebook SDK 12 from this plugin) I had occasions in which the Facebook API would somehow return extremely high expiry timestamps (e.g. literally 9223372036854775807) when calling their `getCurrentAccessToken()`. Super weird, but this response of FB would make my app crash as the Dart `DateTime.fromMillisecondsSinceEpoch()` function has a max input value of `8640000000000000`. _Of course, when try/catching this, it would assume I was not logged in, and therefore not able to use the Facebook integration._

Therefore, I added a check/safeguard to make parsing the Facebook response more resilient. Thus, in case the Facebook API returns crazy high values like above, it will be using the max for parsing to the Dart FacebookAccessToken and prevent the `millisecondsSinceEpoch Invalid value: Not in inclusive range` error.

2021-12-22 12:59 UTC, rogiervandenberg commented
Weird that these checks are failing, even though I totally did not change anything with the imports 🤔  Is this checking more strict than earlier?

2021-12-22 15:33 UTC, greymag commented on lib/src/models/facebook_access_token.dart
> +            map['expires'] as int > 8640000000000000
Let's save this value in const with self-explanatory name

2021-12-22 15:33 UTC, greymag requested changes
Hey! Thanks for the RP. I have just one suggestion

2021-12-22 15:34 UTC, greymag commented
> Weird that these checks are failing, even though I totally did not change anything with the imports 🤔 Is this checking more strict than earlier?

Yes, I'll fix it

2022-02-28 14:28 UTC, greymag commented
No response, so I fixed it myself in [1.4.1](https://pub.dev/packages/flutter_login_facebook/versions/1.4.1). But thanks for point out anyway.

2022-02-28 14:28 UTC, closed without merging